apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}-api
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "api"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "api"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/bin/gunicorn", "backend.wsgi:application", "-R", "--error-logfile", "-", "--log-level", "debug" ]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - import urllib.request;urllib.request.urlopen("http://127.0.0.1:8000/api/todos/")
            failureThreshold: 3
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/
              port: http
            failureThreshold: 3
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints}}
      topologySpreadConstraints:
      {{- range $tscontstraint := . }}
        {{- if $tscontstraint.labelSelector }}
        - {{- toYaml $tscontstraint | nindent 10 }}
        {{- else }}
        - labelSelector:
            matchLabels:
            {{- include "backend.selectorLabels" $ | nindent 14 }}
        {{- toYaml $tscontstraint | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
